#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gdk-pixbuf
Version  : 2.40.0
Release  : 61
URL      : https://download.gnome.org/sources/gdk-pixbuf/2.40/gdk-pixbuf-2.40.0.tar.xz
Source0  : https://download.gnome.org/sources/gdk-pixbuf/2.40/gdk-pixbuf-2.40.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: gdk-pixbuf-bin = %{version}-%{release}
Requires: gdk-pixbuf-data = %{version}-%{release}
Requires: gdk-pixbuf-lib = %{version}-%{release}
Requires: gdk-pixbuf-libexec = %{version}-%{release}
Requires: gdk-pixbuf-license = %{version}-%{release}
Requires: gdk-pixbuf-locales = %{version}-%{release}
Requires: gdk-pixbuf-man = %{version}-%{release}
Requires: librsvg-lib
Requires: shared-mime-info
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-dev32
BuildRequires : libpng-dev32
BuildRequires : librsvg
BuildRequires : librsvg-dev
BuildRequires : librsvg-dev32
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(32libffi)
BuildRequires : pkgconfig(32libpng)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(shared-mime-info)
BuildRequires : pkgconfig(x11)
BuildRequires : qemu
BuildRequires : shared-mime-info
BuildRequires : shared-mime-info-dev
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
Patch1: mime-fallback.patch

%description
The code in this directory implements optimized, filtered scaling
for pixmap data.

%package bin
Summary: bin components for the gdk-pixbuf package.
Group: Binaries
Requires: gdk-pixbuf-data = %{version}-%{release}
Requires: gdk-pixbuf-libexec = %{version}-%{release}
Requires: gdk-pixbuf-license = %{version}-%{release}

%description bin
bin components for the gdk-pixbuf package.


%package data
Summary: data components for the gdk-pixbuf package.
Group: Data

%description data
data components for the gdk-pixbuf package.


%package dev
Summary: dev components for the gdk-pixbuf package.
Group: Development
Requires: gdk-pixbuf-lib = %{version}-%{release}
Requires: gdk-pixbuf-bin = %{version}-%{release}
Requires: gdk-pixbuf-data = %{version}-%{release}
Provides: gdk-pixbuf-devel = %{version}-%{release}
Requires: gdk-pixbuf = %{version}-%{release}

%description dev
dev components for the gdk-pixbuf package.


%package dev32
Summary: dev32 components for the gdk-pixbuf package.
Group: Default
Requires: gdk-pixbuf-lib32 = %{version}-%{release}
Requires: gdk-pixbuf-bin = %{version}-%{release}
Requires: gdk-pixbuf-data = %{version}-%{release}
Requires: gdk-pixbuf-dev = %{version}-%{release}

%description dev32
dev32 components for the gdk-pixbuf package.


%package lib
Summary: lib components for the gdk-pixbuf package.
Group: Libraries
Requires: gdk-pixbuf-data = %{version}-%{release}
Requires: gdk-pixbuf-libexec = %{version}-%{release}
Requires: gdk-pixbuf-license = %{version}-%{release}

%description lib
lib components for the gdk-pixbuf package.


%package lib32
Summary: lib32 components for the gdk-pixbuf package.
Group: Default
Requires: gdk-pixbuf-data = %{version}-%{release}
Requires: gdk-pixbuf-license = %{version}-%{release}

%description lib32
lib32 components for the gdk-pixbuf package.


%package libexec
Summary: libexec components for the gdk-pixbuf package.
Group: Default
Requires: gdk-pixbuf-license = %{version}-%{release}

%description libexec
libexec components for the gdk-pixbuf package.


%package license
Summary: license components for the gdk-pixbuf package.
Group: Default

%description license
license components for the gdk-pixbuf package.


%package locales
Summary: locales components for the gdk-pixbuf package.
Group: Default

%description locales
locales components for the gdk-pixbuf package.


%package man
Summary: man components for the gdk-pixbuf package.
Group: Default

%description man
man components for the gdk-pixbuf package.


%prep
%setup -q -n gdk-pixbuf-2.40.0
cd %{_builddir}/gdk-pixbuf-2.40.0
%patch1 -p1
pushd ..
cp -a gdk-pixbuf-2.40.0 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580441099
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dtiff=false  builddir
ninja -v -C builddir
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain -Dtiff=false  builddir
ninja -v -C builddir
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :
cd ../build32;
meson test -C builddir || : || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gdk-pixbuf
cp %{_builddir}/gdk-pixbuf-2.40.0/COPYING %{buildroot}/usr/share/package-licenses/gdk-pixbuf/01a6b4bf79aca9b556822601186afab86e8c4fbf
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gdk-pixbuf
## install_append content
cp %{_libdir}/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so %{buildroot}%{_libdir}/gdk-pixbuf-2.0/2.10.0/loaders/.
LD_LIBRARY_PATH=%{buildroot}%{_libdir} %{buildroot}%{_bindir}/gdk-pixbuf-query-loaders %{buildroot}%{_libdir}/gdk-pixbuf-2.0/2.10.0/loaders/lib*.so | sed "s@%{buildroot}@@g" > %{buildroot}%{_libdir}/gdk-pixbuf-2.0/2.10.0/loaders.cache
rm %{buildroot}%{_libdir}/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so
sed -e 's/lib64/lib32/g' %{buildroot}%{_libdir}/gdk-pixbuf-2.0/2.10.0/loaders.cache > %{buildroot}/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders.cache

## install_append end

%files
%defattr(-,root,root,-)
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders.cache
/usr/lib32/girepository-1.0/GdkPixbuf-2.0.typelib
/usr/lib32/girepository-1.0/GdkPixdata-2.0.typelib
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache

%files bin
%defattr(-,root,root,-)
/usr/bin/gdk-pixbuf-csource
/usr/bin/gdk-pixbuf-pixdata
/usr/bin/gdk-pixbuf-query-loaders
/usr/bin/gdk-pixbuf-thumbnailer

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GdkPixbuf-2.0.typelib
/usr/lib64/girepository-1.0/GdkPixdata-2.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/installed-tests/gdk-pixbuf/animation.test
/usr/share/installed-tests/gdk-pixbuf/cve-2015-4491.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-area-updated.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-composite.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-construction.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-dpi.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-fail.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-gif-circular-table.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-gif.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-icc.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-icon-serialize.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-jpeg.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-pixdata.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-randomly-modified.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-readonly-to-mutable.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-reftest.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-resource.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-save.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-scale-two-step.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-scale.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-short-gif-write.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-stream.test
/usr/share/installed-tests/gdk-pixbuf/pixbuf-threads.test
/usr/share/thumbnailers/gdk-pixbuf-thumbnailer.thumbnailer

%files dev
%defattr(-,root,root,-)
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf-xlib/gdk-pixbuf-xlib.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf-xlib/gdk-pixbuf-xlibrgb.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-animation.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-autocleanups.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-features.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-io.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-loader.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-macros.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-marshal.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-transform.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h
/usr/lib64/libgdk_pixbuf-2.0.so
/usr/lib64/libgdk_pixbuf_xlib-2.0.so
/usr/lib64/pkgconfig/gdk-pixbuf-2.0.pc
/usr/lib64/pkgconfig/gdk-pixbuf-xlib-2.0.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libgdk_pixbuf-2.0.so
/usr/lib32/libgdk_pixbuf_xlib-2.0.so
/usr/lib32/pkgconfig/32gdk-pixbuf-2.0.pc
/usr/lib32/pkgconfig/32gdk-pixbuf-xlib-2.0.pc
/usr/lib32/pkgconfig/gdk-pixbuf-2.0.pc
/usr/lib32/pkgconfig/gdk-pixbuf-xlib-2.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so
/usr/lib64/libgdk_pixbuf-2.0.so.0
/usr/lib64/libgdk_pixbuf-2.0.so.0.4000.0
/usr/lib64/libgdk_pixbuf_xlib-2.0.so.0
/usr/lib64/libgdk_pixbuf_xlib-2.0.so.0.4000.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so
/usr/lib32/libgdk_pixbuf-2.0.so.0
/usr/lib32/libgdk_pixbuf-2.0.so.0.4000.0
/usr/lib32/libgdk_pixbuf_xlib-2.0.so.0
/usr/lib32/libgdk_pixbuf_xlib-2.0.so.0.4000.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/installed-tests/gdk-pixbuf/1_partyanimsm2.gif
/usr/libexec/installed-tests/gdk-pixbuf/aero.gif
/usr/libexec/installed-tests/gdk-pixbuf/animation
/usr/libexec/installed-tests/gdk-pixbuf/bug143608-comment.jpg
/usr/libexec/installed-tests/gdk-pixbuf/bug725582-testrotate.jpg
/usr/libexec/installed-tests/gdk-pixbuf/bug725582-testrotate.png
/usr/libexec/installed-tests/gdk-pixbuf/bug753605-atsize.jpg
/usr/libexec/installed-tests/gdk-pixbuf/bug775218.jpg
/usr/libexec/installed-tests/gdk-pixbuf/bug775229.pixdata
/usr/libexec/installed-tests/gdk-pixbuf/bug775693.pixdata
/usr/libexec/installed-tests/gdk-pixbuf/cve-2015-4491
/usr/libexec/installed-tests/gdk-pixbuf/cve-2015-4491.bmp
/usr/libexec/installed-tests/gdk-pixbuf/dpi.jpeg
/usr/libexec/installed-tests/gdk-pixbuf/dpi.png
/usr/libexec/installed-tests/gdk-pixbuf/dpi.tiff
/usr/libexec/installed-tests/gdk-pixbuf/icc-profile.jpeg
/usr/libexec/installed-tests/gdk-pixbuf/icc-profile.png
/usr/libexec/installed-tests/gdk-pixbuf/large.jpg
/usr/libexec/installed-tests/gdk-pixbuf/large.png
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-area-updated
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-composite
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-construction
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-dpi
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-fail
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-gif
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-gif-circular-table
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-icc
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-icon-serialize
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-jpeg
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-pixdata
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-randomly-modified
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-readonly-to-mutable
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-reftest
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-resource
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-save
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-scale
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-scale-two-step
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-short-gif-write
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-stream
/usr/libexec/installed-tests/gdk-pixbuf/pixbuf-threads
/usr/libexec/installed-tests/gdk-pixbuf/premature-end.jpg
/usr/libexec/installed-tests/gdk-pixbuf/premature-end.png
/usr/libexec/installed-tests/gdk-pixbuf/test-animation.ani
/usr/libexec/installed-tests/gdk-pixbuf/test-animation.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-image-rle.pixdata
/usr/libexec/installed-tests/gdk-pixbuf/test-image.pixdata
/usr/libexec/installed-tests/gdk-pixbuf/test-image.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/CVE-2017-2862.jpg
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/DoS.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/androstanRezeptor.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug776694.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug777315.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug778204.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug778584.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug779012.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug779016-infinite.icns
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug780269.tif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug784903-overflow-dimensions.tiff
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug785973.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/bug793470-crasher.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/colormap-image-without-colormap.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/empty-file.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/file3.jp2
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.1.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.1.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.1.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.1.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.1.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.2.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.2.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.2.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.3.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.3.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.3.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.3.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.4.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.4.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.5.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.6.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.7.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/invalid.8.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/issue-95-too-narrow.xpm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/issue-95-too-short.xpm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/issue-95.xpm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/fail/overflow.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/255-codes.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/255-codes.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/4095-codes-clear.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/4095-codes-clear.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/4095-codes.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/4095-codes.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/TESTS
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-blues.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-blues.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-blues.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-blues.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-greens.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-greens.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-greens.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-greens.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-reds.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-reds.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-reds.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/all-reds.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.0.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.0.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.1.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.1.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.2.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.2.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.3.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-erase.3.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.0.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.0.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.1.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.1.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.2.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.2.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.3.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-fill.3.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-multi-image-explicit-zero-delay.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-multi-image-explicit-zero-delay.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-multi-image.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-multi-image.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-no-delays.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-no-delays.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-speed.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-speed.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-zero-delays.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation-zero-delays.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.0.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.0.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.1.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.1.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.2.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.2.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.3.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.3.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/animation.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/checkerboard.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/checkerboard.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/comment.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/comment.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth1.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth1.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth2.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth2.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth3.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth3.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth4.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth4.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth5.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth5.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth6.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth6.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth7.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth7.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth8.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/depth8.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/disabled-transparent.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/disabled-transparent.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-keep.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-keep.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-none.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-none.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-restore-background.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-restore-background.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-restore-previous.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/dispose-restore-previous.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/double-clears.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/double-clears.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/empty.icc
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/empty.xmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/extra-data.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/extra-data.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/extra-pixels.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/extra-pixels.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/four-colors-transparent.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/four-colors-transparent.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/four-colors.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/four-colors.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/four-colors.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/four-colors.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/gif87a-animation.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/gif87a-animation.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/gif87a.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/gif87a.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/high-color.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/high-color.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/high-color.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/high-color.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/icc-color-profile-empty.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/icc-color-profile-empty.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/icc-color-profile.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/icc-color-profile.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-inside-bg.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-inside-bg.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-inside-bg.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-inside-bg.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-outside-bg.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-outside-bg.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-outside-bg.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-outside-bg.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-overlap-bg.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-overlap-bg.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-overlap-bg.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-overlap-bg.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-zero-height.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-zero-height.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-zero-size.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-zero-size.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-zero-width.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/image-zero-width.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/images-combine.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/images-combine.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/images-overlap.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/images-overlap.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/interlace.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/interlace.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-ascii-comment.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-ascii-comment.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-background.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-background.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-colors.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-colors.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-transparent.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-transparent.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-utf8-comment.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/invalid-utf8-comment.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/large-codes.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/large-codes.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/large-comment.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/large-comment.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/local-color-table.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/local-color-table.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-animexts.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-animexts.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-buffer.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-buffer.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-buffer_max.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-buffer_max.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-infinite.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-infinite.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-max.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-max.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-once.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/loop-once.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/many-clears.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/many-clears.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-codes.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-codes.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-height.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-height.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-height.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-height.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-size.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-size.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-width.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-width.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-width.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/max-width.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/missing-pixels.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/missing-pixels.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/missing-pixels.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/missing-pixels.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-clear-and-eoi.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-clear-and-eoi.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-clear.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-clear.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-data.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-data.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-eoi.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-eoi.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-global-color-table.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/no-global-color-table.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/nul-application-extension.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/nul-application-extension.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/nul-comment.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/nul-comment.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/plain-text.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/plain-text.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/random-image.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/random-image.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/random_image.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/sRGB.icc
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/test.xmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/transparent-dot.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/transparent-dot.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/transparent.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/transparent.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/unknown-application-extension.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/unknown-application-extension.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/unknown-extension.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/unknown-extension.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/white-dot.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/white-dot.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/white-hline2.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/white-hline2.rgba
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/xmp-data-empty.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/xmp-data-empty.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/xmp-data.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/xmp-data.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/zero-height.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/zero-height.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/zero-size.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/zero-size.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/zero-width.conf
/usr/libexec/installed-tests/gdk-pixbuf/test-images/gif-test-suite/zero-width.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bad-header.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bmp-line-overflow.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bug775232.pnm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bug775242.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bug775648.qtif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bug775697.jpg
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/bug776040.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/crash.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/decodecolormap.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/invalid.1.xpm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/invalid.2.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/invalid.4.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.gif
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.jp2
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.jpeg
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.tiff
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.xbm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.1.xpm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.2.jpeg
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.2.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.2.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.3.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/randomly-modified/valid.4.ppm
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/bug696331.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/bug696331.png.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/bug785447.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/bug785447.ico.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/cat.jpg
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/cat.jpg.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/colormap-too-small.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/colormap-too-small.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/mandatory-bitmasks.bmp
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/mandatory-bitmasks.bmp.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/rle-too-many-pixels-2.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/rle-too-many-pixels-2.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/rle-too-many-pixels.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/rle-too-many-pixels.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/squares.ico
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/squares.ico.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-16bpp.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-24bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-32bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-8bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap-rle-8bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-cmap.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-16bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-8bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-opaque.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-16bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray-rle-8bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-gray.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-opaque.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-24bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-bottom-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-bottom-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-bottom-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-bottom-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-top-left.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-top-left.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-top-right.tga
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo-rle-32bpp-top-right.tga.ref.png
/usr/libexec/installed-tests/gdk-pixbuf/test-images/reftests/tga/gtk-logo.ref.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gdk-pixbuf/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gdk-pixbuf-csource.1
/usr/share/man/man1/gdk-pixbuf-query-loaders.1

%files locales -f gdk-pixbuf.lang
%defattr(-,root,root,-)

